# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Undistro < Formula
  desc "UnDistro is a vanilla, non-opinionated, and open source Kubernetes distribution"
  homepage "https://undistro.io"
  version "0.29.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/getupio-undistro/undistro/releases/download/v0.29.0/undistro_0.29.0_darwin_amd64.tar.gz"
    sha256 "bcdcf00e1f46a05fec014bf7615f13653fb31335b04ba21e7eebd0e14ff17889"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/getupio-undistro/undistro/releases/download/v0.29.0/undistro_0.29.0_darwin_arm64.tar.gz"
    sha256 "d068982b6e28c3ea75dcda40dcc8514a32e79d3a1432eb3f7ad894d8db76ada3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/getupio-undistro/undistro/releases/download/v0.29.0/undistro_0.29.0_linux_amd64.tar.gz"
    sha256 "9eeaca9c8231ebec45a309559b12005e627143bd3437300833d2205af113d5c5"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/getupio-undistro/undistro/releases/download/v0.29.0/undistro_0.29.0_linux_arm64.tar.gz"
    sha256 "50359bf5bba7564a96ed4c8382daf24609cbd743fbefc40903917127f57ce1c7"
  end

  def install
    bin.install "undistro"
  end
end
