# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Undistro < Formula
  desc "UnDistro is a vanilla, non-opinionated, and open source Kubernetes distribution"
  homepage "https://undistro.io"
  version "0.30.4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getupio-undistro/undistro/releases/download/v0.30.4/undistro_0.30.4_darwin_amd64.tar.gz"
      sha256 "f440f75f4d46e1eb71350f6177fb675f4879dc796bb2d50bb0590a28263c001b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/getupio-undistro/undistro/releases/download/v0.30.4/undistro_0.30.4_darwin_arm64.tar.gz"
      sha256 "4e96928e6fcdedb03329593e1f6f575dfc6b628a1570cb9924d31e3f61a7ca43"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/getupio-undistro/undistro/releases/download/v0.30.4/undistro_0.30.4_linux_amd64.tar.gz"
      sha256 "958cfd70f795fe5db2aa8146c1576a5954072a696c8a39d798fd89fdaf2fdc28"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getupio-undistro/undistro/releases/download/v0.30.4/undistro_0.30.4_linux_arm64.tar.gz"
      sha256 "d9bac535d63c2faf905d9b15a62b7d3784302848fdc398da24c16f067ebb3154"
    end
  end

  def install
    bin.install "undistro"
  end
end
